#!/bin/bash

UPSTREAM_IMAGE_DIR=~/.local/share/libvirt/images/upstream
mkdir -p ${UPSTREAM_IMAGE_DIR}

curl -L -o ${UPSTREAM_IMAGE_DIR}/ubuntu-16.04.qcow2 https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
virt-sysprep -a ${UPSTREAM_IMAGE_DIR}/ubuntu-16.04.qcow2 --network --install qemu-guest-agent

curl -L -o ${UPSTREAM_IMAGE_DIR}/ubuntu-18.04.qcow2 https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
update-grub because of https://bugs.launchpad.net/cloud-images/+bug/1726476
virt-sysprep -a ${UPSTREAM_IMAGE_DIR}/ubuntu-18.04.qcow2 --network --install qemu-guest-agent --run-command update-grub

#curl -L -o ${UPSTREAM_IMAGE_DIR}/fedora-29.qcow2 https://download.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2
network-scripts because of https://bugs.launchpad.net/cloud-init/+bug/1799301
virt-sysprep -a ${UPSTREAM_IMAGE_DIR}/fedora-29.qcow2 --network --update --install qemu-guest-agent,network-scripts --run-command 'systemctl enable qemu-guest-agent' --selinux-relabel

curl -L -o ${UPSTREAM_IMAGE_DIR}/centos-7.qcow2 https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
virt-sysprep -v -x -a ${UPSTREAM_IMAGE_DIR}/centos-7.qcow2 --network --update --selinux-relabel

curl -L -o ${UPSTREAM_IMAGE_DIR}/rhel-7.6.qcow2 http://download-node-02.eng.bos.redhat.com/released/RHEL-7/7.6/Server/x86_64/images/rhel-guest-image-7.6-210.x86_64.qcow2
curl -L -o ${UPSTREAM_IMAGE_DIR}/rhel-7.5.qcow2 http://download-node-02.eng.bos.redhat.com/released/RHEL-7/7.5/Server/x86_64/images/rhel-guest-image-7.5-146.x86_64.qcow2
curl -L -o ${UPSTREAM_IMAGE_DIR}/rhel-7.4.qcow2 http://download-node-02.eng.bos.redhat.com/released/RHEL-7/7.4/Server/x86_64/images/rhel-guest-image-7.4-191.x86_64.qcow2

curl -L -o ${UPSTREAM_IMAGE_DIR}/debian-9.qcow2 https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
virt-sysprep -a ${UPSTREAM_IMAGE_DIR}/debian-9.qcow2 --network --install qemu-guest-agent

# Prepare the no-cloud-init flavor
#for image in $(find ${UPSTREAM_IMAGE_DIR} -not -name '*no-cloud-init.qcow2' -type f -exec basename '{}' \;|sed 's,.qcow2,,'); do
# for image in $(echo debian-9.qcow2|sed 's,.qcow2,,'); do
#     (
#         cd ${UPSTREAM_IMAGE_DIR}
#         qemu-img create -f qcow2 -b ${image}.qcow2 ${image}-no-cloud-init.qcow2
#         virt-sysprep -a ${image}-no-cloud-init.qcow2 -root-password password:root --uninstall cloud-init --run-command "/usr/sbin/useradd -m $USER" --run-command "echo $USER ALL=\(ALL\) NOPASSWD:ALL > /etc/sudoers.d/99_$USER" --ssh-inject root:file:$HOME/.ssh/id_rsa.pub --ssh-inject $USER:file:$HOME/.ssh/id_rsa.pub --selinux-relabel
#     )
# done
