#!/bin/bash
set -eux
git clean -ffdx
tox
git clean -ffdx
git tag -s $VERSION
python3 setup.py sdist bdist_wheel
python3 -m twine upload --verbose --repository-url https://upload.pypi.org/legacy/ dist/*
